// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqNcepfDrMyzkFNeRDs19IZa4GOf63EA',
    appId: '1:374523963270:web:fbdee8c5004cad1f81ee07',
    messagingSenderId: '374523963270',
    projectId: 'attandance-app-f6dce',
    authDomain: 'attandance-app-f6dce.firebaseapp.com',
    storageBucket: 'attandance-app-f6dce.firebasestorage.app',
    measurementId: 'G-E792KD62WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNLcuehXLKFM9Xjpx33cGVtvT67HXwiDQ',
    appId: '1:374523963270:android:5d765dd68411117c81ee07',
    messagingSenderId: '374523963270',
    projectId: 'attandance-app-f6dce',
    storageBucket: 'attandance-app-f6dce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMeAe0fKYO3gumGofFXqG1sBByGIoAwI',
    appId: '1:374523963270:ios:c2bdbfba4bf786ef81ee07',
    messagingSenderId: '374523963270',
    projectId: 'attandance-app-f6dce',
    storageBucket: 'attandance-app-f6dce.firebasestorage.app',
    iosBundleId: 'com.example.attandanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvqNcepfDrMyzkFNeRDs19IZa4GOf63EA',
    appId: '1:374523963270:web:57e9f1c269f35ff681ee07',
    messagingSenderId: '374523963270',
    projectId: 'attandance-app-f6dce',
    authDomain: 'attandance-app-f6dce.firebaseapp.com',
    storageBucket: 'attandance-app-f6dce.firebasestorage.app',
    measurementId: 'G-K46MH8WX23',
  );
}
